export const GENDER_OPTIONS = [
  { value: "MALE", label: "Male" },
  { value: "FEMALE", label: "Female" },
  { value: "OTHER", label: "Other" },
];

export const DOCTOR_GENDER_OPTIONS = [
  { value: "Male", label: "Male" },
  { value: "Female", label: "Female" },
  { value: "Other", label: "Other" },
];

export const DOCTOR_SPECIALIZATION_OPTIONS = [
  { value: "General Medicine", label: "General Medicine" },
  { value: "General Physician", label: "General Physician" },
  { value: "Cardiology", label: "Cardiology" },
  { value: "Neurology", label: "Neurology" },
  { value: "Orthopedics", label: "Orthopedics" },
  { value: "Pediatrics", label: "Pediatrics" },
  { value: "Dermatology", label: "Dermatology" },
  { value: "Ophthalmology", label: "Ophthalmology" },
  { value: "ENT", label: "ENT (Ear, Nose, Throat)" },
  { value: "Gastroenterology", label: "Gastroenterology" },
  { value: "Pulmonology", label: "Pulmonology" },
  { value: "Endocrinology", label: "Endocrinology" },
  { value: "Nephrology", label: "Nephrology" },
  { value: "Urology", label: "Urology" },
  { value: "Gynecology", label: "Gynecology" },
  { value: "Psychiatry", label: "Psychiatry" },
  { value: "Oncology", label: "Oncology" },
  { value: "Radiology", label: "Radiology" },
  { value: "Anesthesiology", label: "Anesthesiology" },
  { value: "Pathology", label: "Pathology" },
  { value: "Emergency Medicine", label: "Emergency Medicine" },
  { value: "Sports Medicine", label: "Sports Medicine" },
  { value: "Rheumatology", label: "Rheumatology" },
  { value: "Geriatrics", label: "Geriatrics" },
  { value: "Family Medicine", label: "Family Medicine" },
  { value: "Cosmetic Surgery", label: "Cosmetic Surgery" },
  { value: "Plastic Surgery", label: "Plastic Surgery" },
  { value: "Vascular Surgery", label: "Vascular Surgery" },
  { value: "Cardiac Surgery", label: "Cardiac Surgery" },
  { value: "Neuro Surgery", label: "Neuro Surgery" },
  { value: "Pediatric Surgery", label: "Pediatric Surgery" },
  { value: "Gastrointestinal Surgery", label: "Gastrointestinal Surgery" },
  { value: "Obstetrics", label: "Obstetrics" },
  { value: "Neonatology", label: "Neonatology" },
  { value: "Immunology", label: "Immunology" },
  { value: "Infectious Disease", label: "Infectious Disease" },
  { value: "Internal Medicine", label: "Internal Medicine" },
  { value: "Ayurveda", label: "Ayurveda" },
  { value: "Homeopathy", label: "Homeopathy" },
  { value: "Unani", label: "Unani" },
  { value: "Yoga", label: "Yoga" },
  { value: "Physiotherapy", label: "Physiotherapy" },
  { value: "Dentistry", label: "Dentistry" },
  { value: "Dental Surgery", label: "Dental Surgery" },
  { value: "Orthodontics", label: "Orthodontics" },
  { value: "Oral Surgery", label: "Oral Surgery" },
  { value: "Periodontics", label: "Periodontics" },
  { value: "Endodontics", label: "Endodontics" },
  { value: "Prosthodontics", label: "Prosthodontics" },
  { value: "Other", label: "Other" },
];
